### ISSUE TITLE
If the implementation of art two-dimensional code, how will you operate

### ISSUE THREAD

**Issue by fenglijunnb** [sheirys/qrcode#1]
![it399 com qrcode2](https://user-images.githubusercontent.com/48191768/77416110-71684100-6dfe-11ea-9884-ffa836eabcc4.jpg)

**Comment by sheirys** [comment]
Hi, thanks for issue @fenglijunnb. Please keep in mind:

1. This is QR code generator, not reader.
2. This repository is wrapper for https://github.com/boombuler/barcode. Any additional functionality should be discussed there.

I will close this issue because of second reason. Thanks again!
